name = "GlobalOpt"
uuid = "1d622bb0-3e75-4b2d-9dc1-f9174e972a2b"
authors = ["F. Capolupo"]
version = "0.1.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
